{
  "openapi": "3.1.0",
  "info": {
    "title": "eraiyomi RESTful API",
    "description": "OpenAPI for eraiyomi",
    "version": "1",
    "contact": {
      "name": "Patrick Chen",
      "email": "patrick.chen31@gmail.com",
      "url": "eraiyomi.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8000/api",
      "description": "development"
    },
    {
      "url": "https://eraiyomi-server.up.railway.app/api",
      "description": "production"
    }
  ],
  "components": {
    "parameters": {
      "ArticleIdParam": {
        "name": "articleId",
        "description": "The article's id for performing CRUD operation",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "CommentId": {
        "name": "commentId",
        "description": "The comment's id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    },
    "schemas": {
      "Article": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "titleArticle": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                },
                "URLpath": {
                  "type": "string"
                }
              }
            }
          },
          "shortDescription": {
            "type": "string"
          },
          "publishedDate": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "published",
              "unpublished"
            ]
          },
          "editHistory": {
            "type": "object",
            "properties": {
              "date": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "likeDislike": {
            "type": "object",
            "properties": {
              "totalLike": {
                "type": "integer"
              },
              "totalDislike": {
                "type": "integer"
              },
              "users": {
                "type": "object",
                "additionalProperties": {
                  "type": "boolean"
                }
              }
            }
          },
          "author": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "category": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "articleAssetIdRef": {
            "type": "string"
          },
          "__v": {
            "type": "integer"
          }
        }
      },
      "ArticleAssetModel": {
        "type": "object",
        "properties": {
          "articleIdRef": {
            "type": "string"
          },
          "thumbnail": {},
          "content": {
            "type": [],
            "items": {
              "type": "object"
            }
          },
          "totalWordCounts": {
            "type": "number"
          }
        },
        "required": [
          "articleIdRef",
          "content",
          "totalWordCounts"
        ]
      },
      "UserModel": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "userId": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "profilePictureUrl": {
            "type": "string"
          }
        }
      }
    }
  },
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "Article"
        ],
        "summary": "Get all article",
        "parameters": [
          {
            "name": "sort",
            "description": "Sort articles with several available options",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "default": "latest",
              "enum": [
                "latest",
                "earliest",
                "popular",
                "unpopular"
              ]
            }
          },
          {
            "name": "status",
            "description": "get articles based on its status",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "default": "all",
              "enum": [
                "all",
                "published",
                "unpublished"
              ]
            }
          },
          {
            "name": "search",
            "in": "query",
            "description": "search an article based on given keyword from user and will be matched with article's title",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success get all article",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Article"
                }
              }
            }
          },
          "500": {
            "description": "fail on fetching data article from database",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "value": {
                      "message": "fail on fetching data article from database"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/article": {
      "get": {
        "tags": [
          "Article"
        ],
        "summary": "Get an individual article",
        "parameters": [
          {
            "$ref": "#/components/parameters/ArticleIdParam"
          },
          {
            "name": "title",
            "in": "query",
            "required": true,
            "description": "search article with given title",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success get $title article",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Article"
                }
              }
            }
          },
          "400": {
            "description": "article not found or given invalid id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "invalid-id": {
                    "value": {
                      "message": "404 Not Found. Article with id ${id} is an invalid id."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "article not found or given invalid id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "invalid-id": {
                    "value": {
                      "message": "404 Not Found. Article with id ${id} is an invalid id."
                    }
                  },
                  "not-found": {
                    "value": {
                      "message": "404 Not Found. Article with id ${id} or title ${title} is not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Article"
        ],
        "summary": "Create an article",
        "requestBody": {
          "description": "The actual content of the article",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "titleArticle": {
                    "type": "object",
                    "properties": {
                      "URLpath": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      }
                    }
                  },
                  "shortDescription": {
                    "type": "string"
                  },
                  "publishedDate": {
                    "type": "string",
                    "default": "yyyy-mm-dd"
                  },
                  "status": {
                    "type": "string",
                    "enum": [
                      "published",
                      "unpublished"
                    ]
                  },
                  "editHistory": {
                    "type": "object",
                    "properties": {
                      "date": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "likeDislike": {
                    "type": "object",
                    "properties": {
                      "totalLike": {
                        "type": "integer",
                        "default": 0
                      },
                      "totalDislike": {
                        "type": "integer",
                        "default": 0
                      },
                      "users": {
                        "type": "object"
                      }
                    }
                  },
                  "author": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "category": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "articleAssetIdRef": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "client request body": {
                  "value": {
                    "title": "Sample Title",
                    "shortDescription": "Sample Short Description",
                    "status": "published",
                    "author": "Sample Author",
                    "email": "sample@example.com",
                    "category": [
                      "Category1",
                      "Category2",
                      "Category(n)"
                    ]
                  }
                },
                "server database model": {
                  "value": {
                    "_id": "1234567890",
                    "titleArticle": {
                      "title": "Sample Title",
                      "URLpath": "sample-title"
                    },
                    "shortDescription": "Sample Short Description",
                    "publishedDate": "yyyy-mm-dd",
                    "status": "published",
                    "editHistory": {
                      "date": []
                    },
                    "likeDislike": {
                      "totalLike": 0,
                      "totalDislike": 0,
                      "users": {}
                    },
                    "author": "Sample Author",
                    "email": "sample@example.com",
                    "category": [
                      "Category1",
                      "Category2"
                    ],
                    "articleAssetIdRef": "12344567"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success create a article",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/Article"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "duplicate title",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object"
                    }
                  }
                },
                "examples": {
                  "duplicate-title": {
                    "value": {
                      "message": "title ${body.title} was already used. Please try another title.",
                      "data": {}
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "error during creation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "creation-error": {
                    "value": {
                      "message": "Error during articleModel.create(). Error during article creation"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Article"
        ],
        "summary": "Edit an article",
        "parameters": [
          {
            "$ref": "#/components/parameters/ArticleIdParam"
          },
          {
            "description": "an action of like or dislike an article",
            "name": "action",
            "in": "query",
            "schema": {
              "type": "string",
              "enum": [
                "like",
                "dislike"
              ]
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "titleArticle": {
                    "type": "object",
                    "properties": {
                      "url": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      }
                    }
                  },
                  "shortDescription": {
                    "type": "string"
                  },
                  "editHistory": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "likeDislike": {
                    "type": "object",
                    "properties": {
                      "totalLike": {
                        "type": "integer"
                      },
                      "totalDislike": {
                        "type": "integer"
                      },
                      "users": {
                        "type": "object",
                        "additionalProperties": {
                          "type": "boolean"
                        }
                      }
                    }
                  },
                  "category": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "content": {
                    "type": "object"
                  }
                }
              },
              "examples": {
                "article-metadata": {
                  "value": {
                    "titleArticle": {
                      "title": "dolor sit amet",
                      "URLpath": "dolor-sit-amet"
                    },
                    "shortDescription": "lorem ipsum",
                    "category": [
                      "lorem",
                      "ipsum"
                    ],
                    "status": "published"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success edit an article",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "$ref": "#/components/schemas/Article"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "article not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "not-found": {
                    "value": {
                      "message": "404 Not Found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Article"
        ],
        "summary": "Delete an article",
        "parameters": [
          {
            "$ref": "#/components/parameters/ArticleIdParam"
          }
        ],
        "responses": {
          "204": {
            "description": "Success deleting an article. The request was successful, but there is no content to return. This status indicates that the deletion operation was successful and the resource is no longer available."
          },
          "404": {
            "description": "article not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "not-found": {
                    "value": {
                      "message": "Article with id ${articleId} is not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/articles-asset": {
      "get": {
        "summary": "get every asset for each article",
        "tags": [
          "Article-asset"
        ],
        "responses": {
          "200": {
            "description": "success get all article",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ArticleAssetModel"
                  }
                }
              }
            }
          },
          "500": {
            "description": "fail on fetching data article's asset from database",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "value": {
                      "message": "500 Server Internal Error. Error when articleAssetModel.find()"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/article-asset": {
      "get": {
        "summary": "get individual article's asset",
        "tags": [
          "Article-asset"
        ],
        "parameters": [
          {
            "name": "id",
            "description": "search by article's id",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success get all article",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ArticleAssetModel"
                }
              }
            }
          },
          "400": {
            "description": "invalid article id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "invalid-id": {
                    "value": {
                      "message": "400 Not Found. article-asset with id ${id} is not found"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "fail fetch article's asset from database",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "not-found-article": {
                    "value": {
                      "message": "404 Not Found. article with id ${id} is not found"
                    }
                  },
                  "not-found-articleAsset": {
                    "value": {
                      "message": "404 Not Found. article-asset with id ${id} is not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "edit individual article's asset",
        "tags": [
          "Article-asset"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": [],
                    "items": {
                      "type": "object"
                    }
                  },
                  "totalWordCounts": {
                    "type": "number"
                  }
                },
                "required": [
                  "totalWordCounts"
                ]
              },
              "examples": {
                "client-req-body": {
                  "value": {
                    "totalWordCounts": 746,
                    "content": [
                      {
                        "insert": "lorem ipsum"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "sucess editing article asset",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "success-1": {
                    "value": {
                      "message": "success editing article asset. article's title ${article.titleArticle.title}"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "invalid article id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "invalid-id": {
                    "value": {
                      "message": "400 Bad Request. Article with id ${articleId} is invalid."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "fail fetch article's asset from database",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "not-found": {
                    "value": {
                      "message": "404 Bad Request. Article with id ${articleId} is not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "fail to upload img into the cloud",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "user"
        ],
        "responses": {
          "200": {
            "description": "success get all registered user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string"
                    },
                    "userId": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "password": {
                      "type": "string"
                    },
                    "profilePictureUrl": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "success-1": {
                    "value": {
                      "_id": "655471d9c4cba51553b5136b",
                      "userId": "d632dbd7-4ff1-4fe9-80e4-a36d52b74ecf",
                      "name": "",
                      "username": "Michael_Nolan",
                      "email": "Toy.Gibson77@hotmail.com",
                      "password": "$2b$10$aQnNeh58AlFMzCOgtWbIieed8Oq92bm6bPIowC0gIvKGnC9uzXnRm",
                      "profilePictureUrl": "https://www.gravatar.com/avatar/?d=mp",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "retrieve an account",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "required": true,
            "description": "search user with given username",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "description": "search user with given email",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success get user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/UserModel"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "invalid-email-username": {
                    "value": {
                      "message": "Either email or username is needed"
                    }
                  },
                  "invalid-email": {
                    "value": {
                      "message": "${email} is detected as not a proper email address"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "not-found": {
                    "value": {
                      "message": "${username||email} does not exist"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "register an account",
        "tags": [
          "user"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "boolean"
                  },
                  "password": {
                    "type": "string"
                  },
                  "profilePictureUrl": {
                    "type": "string"
                  },
                  "registerationMethod": {
                    "type": "string",
                    "enum": [
                      "traditional",
                      "google"
                    ]
                  }
                },
                "required": [
                  "username",
                  "email"
                ]
              },
              "examples": {
                "client-req-body": {
                  "value": {
                    "username": "abcd",
                    "email": "abcd@mail.com",
                    "password": "abcd123",
                    "name": "abcd efg",
                    "profilePictureUrl": "www.image.com",
                    "registerationMethod": "traditional"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success creating a new user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "success-res": {
                    "value": {
                      "message": "success creating a new user"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "invalid-email-username": {
                    "value": {
                      "message": "Either ${username} 'username' or ${email} 'email' is empty. Those are required data to be filled."
                    }
                  },
                  "invalid-username": {
                    "value": {
                      "message": "username '${username}' contains spaces or prohibited character"
                    }
                  },
                  "already-exist": {
                    "value": {
                      "message": "${username} or ${email} is already in use."
                    }
                  },
                  "password-isempty": {
                    "value": {
                      "message": "Password field must not be empty."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "creation-error": {
                    "value": {
                      "message": "something error with the server. Cannot create an user. userModel.create() is error"
                    }
                  },
                  "invalid-datatype": {
                    "value": {
                      "message": "password is not a string"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete user",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "required": true,
            "description": "search user with given id",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Success deleting an article. The request was successful, but there is no content to return. This status indicates that the deletion operation was successful and the resource is no longer available."
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/user/login-traditional": {
      "post": {
        "summary": "login",
        "description": "login with the account that created with register method",
        "tags": [
          "user"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "email": {
                    "type": "boolean"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "client-req-body": {
                  "value": {
                    "username": "abcd",
                    "email": "abcd@mail.com",
                    "password": "abcd123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "_id": {
                        "type": "string"
                      },
                      "userId": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "profilePictureUrl": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "success-with-acc-res": {
                    "value": {
                      "username": "qwerty",
                      "name": "abcd",
                      "email": "abcd@email.com",
                      "pictureURL": "https://pictureurl.com",
                      "accountId": "123456789",
                      "message": "success creating a new account"
                    }
                  }
                }
              }
            },
            "headers": {
              "set-cookie": {
                "description": "Cookie containing user credentials token",
                "schema": {
                  "type": "string"
                },
                "example": "userCredToken=xyz123; Max-Age=3600; HttpOnly; Secure"
              }
            }
          },
          "401": {
            "description": "unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "necessary-data": {
                    "value": {
                      "message": "Please fill in the gap to login"
                    }
                  },
                  "not-found": {
                    "value": {
                      "message": "${username||email} does not exist. Please register to login."
                    }
                  },
                  "incorrect password": {
                    "value": {
                      "message": "Incorrect password"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/verify": {
      "post": {
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "query",
            "required": true,
            "description": "a JWT token that is need to be submitted from the client side",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success verify user identity",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "_id": {
                        "type": "string"
                      },
                      "userId": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "profilePictureUrl": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "success-verify": {
                    "value": {
                      "message": "success verify user identity",
                      "data": {
                        "username": "qwerty",
                        "name": "abcd",
                        "email": "abcd@email.com",
                        "pictureURL": "https://pictureurl.com",
                        "accountId": "123456789"
                      }
                    }
                  }
                }
              }
            },
            "headers": {
              "set-cookie": {
                "description": "Cookie containing user's credentials token",
                "schema": {
                  "type": "string"
                },
                "example": "userCredToken=xyz123; Max-Age=3600; HttpOnly; Secure"
              }
            }
          }
        }
      }
    }
  }
}